MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 21
DATASETS:
  TRAIN: ("voc_2007_train_cocostyle", "voc_2007_val_cocostyle")
  TEST: ("voc_2007_test",)
DATALOADER:
      SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.008 # 0.004
  WEIGHT_DECAY: 0.0001
  STEPS: (6250, ) # (12500, )
  MAX_ITER: 8750 # 17500
  IMS_PER_BATCH: 8 # 4
TEST:
  IMS_PER_BATCH:  4

# OUTPUT_DIR: "output_voc_2007_r50_FPN"
